import deepFreeze from "deep-freeze"

export default deepFreeze({
    // Application
    ADD_LAYER_TO_STACK: "ADD_LAYER_TO_STACK",
    BRING_LAYER_TO_TOP_OF_STACK: "BRING_LAYER_TO_TOP_OF_STACK",
    REMOVE_LAYER_FROM_STACK: "REMOVE_LAYER_FROM_STACK",
    SET_EXPANDED_HABITS: "SET_EXPANDED_HABITS",
    SET_LAYER_VISIBILITY: "SET_LAYER_VISIBILITY",
    SET_SCALE_FILTER: "SET_SCALE_FILTER",

    // Habits
    CREATE_HABIT: "CREATE_HABIT",
    SET_HABITS: "SET_HABITS",

    // Wallpapers
    SET_WALLPAPER_INDEX: "SET_WALLPAPER_INDEX"
})