import deepFreeze from "deep-freeze"

export default deepFreeze({
    // Application
    ADD_LAYER_TO_STACK: "ADD_LAYER_TO_STACK",
    BRING_LAYER_TO_TOP_OF_STACK: "BRING_LAYER_TO_TOP_OF_STACK",
    REMOVE_LAYER_FROM_STACK: "REMOVE_LAYER_FROM_STACK",
    SET_EXPANDED_HABITS: "SET_EXPANDED_HABITS",
    SET_LAYER_VISIBILITY: "SET_LAYER_VISIBILITY",
    SET_SCALE_FILTER: "SET_SCALE_FILTER",

    // Habits
    CREATE_HABIT: "CREATE_HABIT",
    SET_HABITS: "SET_HABITS",
    SET_INVALID_HABIT_NAME: "SET_INVALID_HABIT_NAME",
    SET_INVALID_HABIT_SCALE: "SET_INVALID_HABIT_SCALE",
    SET_VALID_HABIT_DESC: "SET_VALID_HABIT_DESC",
    SET_VALID_HABIT_NAME: "SET_VALID_HABIT_NAME",
    SET_VALID_HABIT_SCALE: "SET_VALID_HABIT_SCALE",

    // Wallpapers
    SET_WALLPAPER_INDEX: "SET_WALLPAPER_INDEX"
})